# prometheus --config.file=prometheus.yaml --web.listen-address="0.0.0.0:8000"

global:
  scrape_interval: 5s # How often to scrape targets by default
  
scrape_configs:
  - job_name: "app_2023mt03008"
    static_configs:
      - targets: ["localhost:8000"]